# Generated by Django 5.2 on 2025-06-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartiItem',
            new_name='CartItem',
        ),
    ]
